version: "3.7"
services:
  # not suceeded
  mesh:
    volumes:
    - ./.meshrc.yaml:/work/.meshrc.yaml
    - ./example-query.graphql:/work/example-query.graphql
    image: hiroyukiosaki/graphql-mesh:latest-all-alpine
    ports:
    - "4000:4000"
  postgres:
    image: postgres
    ports:
    - "5432"
    environment:
    - POSTGRES_PASSWORD=docker
    volumes:
    - ./world.sql:/docker-entrypoint-initdb.d/world.sql
